---
- type: replace
  path: /releases/name=loggregator-agent?
  value:
    name: loggregator-agent
    version: latest

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value: &loggregator_agent_config
    name: loggregator_agent
    release: loggregator-agent
    properties:
      deployment: ((deployment-name))
      loggregator:
        tls:
          ca_cert: ((loggregator-tls-ca-cert))
          agent:
            cert: ((loggregator-tls-metron-cert))
            key: ((loggregator-tls-metron-key))

- type: replace
  path: /instance_groups/name=haproxy/jobs/-
  value: *loggregator_agent_config
