---
- type: replace
  path: /releases/name=loggregator-agent?
  value:
    name: loggregator-agent
    version: latest

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value: &loggregator_agent_config
    name: loggregator_agent
    release: loggregator-agent
    consumes:
      doppler:
        from: doppler
        deployment: ((cf-deployment-name))
    properties:
      deployment: ((deployment-name))
      loggregator:
        tls:
          agent:
            cert: ((loggregator_tls_agent.certificate))
            key: ((loggregator_tls_agent.private_key))
          ca_cert: ((loggregator_tls_agent.ca))
      metrics:
        ca_cert: ((loggregator_agent_metrics_tls.ca))
        cert: ((loggregator_agent_metrics_tls.certificate))
        key: ((loggregator_agent_metrics_tls.private_key))
        server_name: loggregator_agent_metrics

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /instance_groups/name=haproxy/jobs/-
  value: *loggregator_agent_config
