---
- type: replace
  path: /releases/name=loggregator?
  value:
    name: loggregator
    version: latest

- type: replace
  path: /instance_groups/name=rmq/jobs/-
  value: &metron_agent_config
    name: metron_agent
    release: loggregator
    properties:
      metron_agent:
        deployment: ((deployment-name))
      loggregator:
        tls:
          ca_cert: ((loggregator-tls-ca-cert))
          metron:
            cert: ((loggregator-tls-metron-cert))
            key: ((loggregator-tls-metron-key))

- type: replace
  path: /instance_groups/name=haproxy/jobs/-
  value: *metron_agent_config
